<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value ="0.5"/>
    <xacro:property name="base_width" value ="0.5"/>
    <xacro:property name="base_height" value ="0.1"/>
    <xacro:property name="wheel_radius" value ="0.06"/>
    <xacro:property name="wheel_length" value ="0.05"/>
    <xacro:property name="fork_length" value ="0.4"/>
    <xacro:property name="fork_width" value ="0.03"/>
    <xacro:property name="fork_height" value ="0.01"/>
    
    <link name="base_footprint">
        <origin xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia  m="2.0" l="${0.5*base_length}" w="${0.5*base_width}" h="${0.5*base_height}"
                            xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name ="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia  m="0.5" r="${2*wheel_radius}" h="${2*wheel_length}"
                                xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <xacro:macro name="caster_wheel_link" params="prefix">
        <link name ="${prefix}_caster_wheel_link">
            <visual>
                <geometry>
                    <sphere radius="${wheel_radius/2.0}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius/2.0}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" /> 
            </collision>
            <xacro:sphere_inertia m="0.5" r="${2*wheel_radius/2.0}"
                                xyz="0 0 0" rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:caster_wheel_link prefix="front"/>
    <xacro:caster_wheel_link prefix="back"/>

    <xacro:macro name="fork_link" params="prefix">
        <link name ="${prefix}_fork_link">
            <visual>
                <geometry>
                    <box size="${fork_length} ${fork_width} ${fork_height}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <box size="0.4 0.03 0.01"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" /> 
            </collision>
            <xacro:box_inertia  m="0.01" l="${0.5*fork_length}" w="${0.5*fork_width}" h="${0.5*fork_height}"
                                xyz="0 0 ${fork_height/2.0}" rpy="0 0 0"/>
        </link>
    </xacro:macro>

    <xacro:fork_link prefix="left"/>
    <xacro:fork_link prefix="right"/>

    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 ${(-base_width/2.0)-(wheel_length/2.0)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 ${(base_width/2.0)+(wheel_length/2.0)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_front_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_caster_wheel_link"/>
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius/2.0}" rpy="0 0 0" />
    </joint>

    <joint name="base_back_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="back_caster_wheel_link"/>
        <origin xyz="${-base_length / 3.0} 0 ${-wheel_radius/2.0}" rpy="0 0 0" />
    </joint>

    <joint name="base_left_fork_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_fork_link"/>
        <origin xyz="${(base_length/2.0)+0.2} ${(base_width/4.0)-0.02} 0" rpy="0 0 0" />
    </joint>

    <joint name="base_right_fork_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_fork_link"/>
        <origin xyz="${(base_length/2.0)+0.2} ${(-base_width/4.0)+0.02} 0" rpy="0 0 0" />
    </joint>

</robot>