microcontroller:
  idmcu: 1 # id of mcu 
  namespace: "coop_teleop" # namespace
  generate_library_Path: "/home/fang/Arduino/libraries/"  # path for generate library
  connection:
    type: "UART"   # ["UART","UDP"] support 2 mode 1.Serial UART 2.Wifi UDP (Only arduino and esp32)
    serial_port: "/dev/ttyACM0"  # for Serial UART example "/dev/ttyUSB0"
    baudrate: 115200  # for UART


ros: # setup ros is reference from microcontroller example publisher is mean microcontroller publish to ros network
  publisher:  [     [1,"encode", "geometry_msgs/Vector3Stamped.msg"] ,
                    [2,"speedreq", "geometry_msgs/Vector3Stamped.msg"],
                    [3,"PWM", "geometry_msgs/Vector3Stamped.msg"],
                    [4,"speedcmd", "geometry_msgs/Vector3Stamped.msg"],
                    [5,"odom", "geometry_msgs/Pose.msg"]
                       ]
  subscriber: [   [1,"cmd_vel", "geometry_msgs/Twist.msg"]  ]
  srv_client: [                           ]
  srv_server: [                           ]
  action_client: [                        ]
  action_server: [                        ]

